AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 125

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
